apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lunfaaa/argo-test-sonar
    targetRevision: main
    path: . # Asegúrate de que este path sea correcto
  syncPolicy:
    automated: {}
