apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "123qweasd"
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:latest
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "123qweasd"
        - name: KEYCLOAK_DATABASE_HOST
          value: "postgresql"
        - name: KEYCLOAK_DATABASE_PORT
          value: "5432"
        - name: KEYCLOAK_DATABASE_USER
          value: "keycloak"
        - name: KEYCLOAK_DATABASE_PASSWORD
          value: "123qweasd"
        - name: KEYCLOAK_DATABASE_NAME
          value: "keycloak"
        ports:
        - name: http
          containerPort: 8080

